# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80afebcd9a11d20fdb9cd18207124118219a9fc95298e1c067b2056efcc59f2d272c26fefc6dde618ac30a2a9060ec37898bdfd5952c4b150950d2a03fd656a0

test:
  secret_key_base: 45b3e8d1011e84482bef1eabd67b143d7dae9757860406d7b0dc251321c151672fca84351a2f0d6adc36ebfb73c3a5f8d6106dde6ba27b993222a02e21192e01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
